### ISSUE TITLE
Add/Verify OpenOCD VexrRiscv-SMP JTAG Debug.

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/LimeSDR-XTRX_LiteX_GW#3]
- [x] Swtch CPU to VexRiscv-SMP.
- [x] Add/verify support to the target.
- [x] Add local instruction to do JTAG Debugging (from https://github.com/enjoy-digital/litex/wiki/JTAG-GDB-Debugging-with-VexRiscv-SMP-NaxRiscv-VexiiRiscv-CPUs).

**Comment by enjoy-digital** [comment]
Should be done on `litex_xtrx.py` target with BSCAN.

**Comment by enjoy-digital** [comment]
@trabucayre: Can you update, is "Add/verify support to the target." done?

**Comment by trabucayre** [comment]
Done: with `--bscan-option` vexriscv-smp is configured with `privileged-debug`, `hardware-breakpoint=4` and a BSCAN primitive is added/connected

**Comment by enjoy-digital** [comment]
Done.
