### ISSUE TITLE
Firmware flashing/loading to/from SPI Flash. Firmware flashing/loading to/from SPI Flash.

### ISSUE THREAD

**Issue by vbuitvydas** [enjoy-digital/LimeSDR-XTRX_LiteX_GW#8]
When trying to flash firmware to SPI Flash geting with command:

`./limesdr_xtrx.py --with-bscan --board=limesdr --build --flash-boot --flash --cable ft2232`

I am getting:
`litex.build.generic_platform.ConstraintError: Resource not found: spiflash:None`

![image](https://github.com/enjoy-digital/LimeSDR-XTRX_LiteX_GW/assets/25218697/4e28318d-0f9e-46b8-911b-010df4ec163b)

**Comment by vbuitvydas** [comment]
@enjoy-digital

**Comment by enjoy-digital** [comment]
Hi @vbuitvydas,

sorry, just got  the notification. We'll look at it.

**Comment by trabucayre** [comment]
Fixed with https://github.com/enjoy-digital/LimeSDR-XTRX_LiteX_GW/commit/ef15cd20bbad43101e22fe98ef7c8229eb88a23b

**Comment by vbuitvydas** [comment]
Thanks. Now it is working.
